Table User {
    id number [primary key]
    email varchar
    password varchar
    nama varchar
    no_telp varchar
    alamat varchar 
    bucket_id varchar
    created_at datetime
    updated_at datetime
}

Table Seller {
    id number [primary key]
    user_id number
    product_id number
}